syncfusion-content/ej2-common-docs

code-snippet/common/getting-started-cs1/index.ts
code-snippet/common/getting-started-cs1/ts/index.html
code-snippet/common/getting-started-cs2/js/index.html
ej2-javascript-common-toc.html
ts/getting-started/compatible-with-essential-js1.md
ts/getting-started/cordova.md
ts/getting-started/ionic.md
ts/getting-started/meteor.md
ts/getting-started/sharepoint.md

documentation(EJ2-71943): fixed image issue

---

ej2-javascript/appearance/icons.md
ej2-javascript/installation-and-upgrade/installation.md
ej2-javascript/js/getting-started/quick-start.md
ej2-javascript/ts/deployment.md
ej2-javascript/ts/getting-started/quick-start.md
ej2-javascript/ts/getting-started/sharepoint.md

documentation(830451): changed the code alignments

---

ej2-javascript/js/getting-started/compatible-with-essential-js1.md
ej2-javascript/js/getting-started/quick-start.md
ej2-javascript/ts/getting-started/cordova.md
ej2-javascript/ts/getting-started/ionic.md
ej2-javascript/ts/getting-started/meteor.md

documentation(832446): changed the code alignments

---

ej2-javascript/ej2-javascript-common-toc.html
ej2-javascript/ej2-typescript-common-toc.html

documentation(832446):changed release notes version

---

ej2-javascript/ej2-javascript-common-toc.html
ej2-javascript/ej2-typescript-common-toc.html

documentation(832446):changed api reference

---

ej2-javascript/appearance/icons.md
ej2-javascript/appearance/theme.md
ej2-javascript/code-snippet/common/getting-started-cs2/js/index.html
ej2-javascript/js/getting-started/quick-start.md
ej2-javascript/ts/deployment.md
ej2-javascript/ts/getting-started/cordova.md
ej2-javascript/ts/getting-started/ionic.md

CDN version changes committed.

documentation(EJ2-833878): CDN version changes committed.

---

ej2-javascript/common/Troubleshoot/content-security-policy.md
ej2-javascript/ej2-typescript-common-toc.html

documentation(EJ2-835879): Updated toc file.

---

ej2-javascript/js/getting-started/compatible-with-essential-js1.md
ej2-javascript/js/getting-started/webforms.md
ej2-javascript/js/introduction.md
ej2-javascript/ts/getting-started/electron.md
ej2-javascript/ts/getting-started/ionic.md
ej2-javascript/ts/getting-started/meteor.md
ej2-javascript/ts/introduction.md

Need to resolve the reported issues in JS/TS Documentation.
Resolved the issues reported in JS/TS Documentation.
NA
No area is affected due to this changes.
NA
NA

documentation(835697): Resolved Major issues reported in JS and TS Documentation

---

ej2-javascript/common/Troubleshoot/content-security-policy.md
ej2-javascript/common/how-to/csp-errors.md
ej2-javascript/ej2-javascript-common-toc.html
ej2-javascript/ej2-typescript-common-toc.html

CSP content changed committed.

documentation(EJ2-833878): CSP content changed committed.

---

ej2-javascript/appearance/theme.md
ej2-javascript/code-snippet/common/material3-cs1/index.ts
ej2-javascript/code-snippet/common/material3-cs1/ts/index.html
ej2-javascript/ej2-javascript-common-toc.html
ej2-javascript/ej2-typescript-common-toc.html

Corrected the material 3 documentation correction

config(839205): material3 documentation correction

---

ej2-javascript/ts/licensing/licensing-troubleshoot.md

Need to provide information about how to remove the duplicate packages when license issue occurred.
Currently, we have not provided the information on how to remove the duplicate packages in our documentation we have analyzed and provided the steps to remove the duplicate packages to resolve the license issue.
I have added the following steps to remove respective files which causes the duplicate packages get installed in the application.
The changes can be only seen in live.
NA 
Need to ensure this support in manual test cases.
Added the manual test cases for this support.
* Does your new code introduce new …

feature(379285): duplicate packages info in typescript

---

ej2-javascript/ts/licensing/licensing-troubleshoot.md

Need to provide information about how to remove the duplicate packages when license issue occurred.
Currently, we have not provided the information on how to remove the duplicate packages in our documentation we have analyzed and provided the steps to remove the duplicate packages to resolve the license issue.
I have added the following steps to remove respective files which causes the duplicate packages get installed in the application.
The changes can be only seen in live.
NA 
Need to ensure this support in manual test cases.
Added the manual test cases for this support.
* Does your new code introduce new …

379285 tsduplicate

---

ej2-javascript/common/Troubleshoot/content-security-policy.md
ej2-javascript/common/how-to/csp-errors.md

config(EJ2-833878): CSP changes committed.

---

ej2-javascript/installation-and-upgrade/installation-using-offline-installer.md
ej2-javascript/js/introduction.md
ej2-javascript/js/licensing/overview.md
ej2-javascript/ts/introduction.md

Resolved the broken links issues in Common documentation.
Resolved the broken links in introduction, overview, installation and upgrade topic
NA
No area is affected due to this changes.
NA
NA

bug(839526): Resolved broken link issue for common repository

---

ej2-javascript/installation-and-upgrade/installation-using-offline-installer.md
ej2-javascript/js/introduction.md
ej2-javascript/js/licensing/overview.md
ej2-javascript/ts/introduction.md

Resolved broken links issue for Common documentation

bug(839526): Resolved broken link issue for Common documentation

---

ej2-javascript/code-snippet/common/locale-cs1/js/index.html
ej2-javascript/code-snippet/common/locale-cs1/ts/index.html
ej2-javascript/code-snippet/common/right-to-left-cs1/js/index.html
ej2-javascript/code-snippet/common/right-to-left-cs2/js/index.html
ej2-javascript/code-snippet/common/script-template-cs1/js/index.html
ej2-javascript/code-snippet/common/script-template-cs1/ts/index.html
ej2-javascript/code-snippet/common/state-persistence-template-cs1/index.js
ej2-javascript/code-snippet/common/state-persistence-template-cs1/js/index.html

Need to resolve the preview samples rendering issue in JS/TS Documentation.
Resolved the preview samples breakage issue for the following topics:
**JavaScript Documentation**
1) Right-to-Left
2) State Persistence
3)Template
4) Localization
**TypeScript Documentation**
1) Template
2) Localization
NA
No area is affected due to this changes.
NA
NA

documentation(838323: Resolved the preview samples breaking issue in JS/TS docs

---

ej2-javascript/appearance/theme.md

839603- Added proper CDN link

---

ej2-javascript/js/introduction.md
ej2-javascript/ts/introduction.md

| Title | Description |
| -------- | -------- |
|**Task Link**|https://dev.azure.com/Syncfusion-Infrastructure/Install/_workitems/edit/174643|
|**Analysis and design**|1. Analyzed the details in the task.<br/>2. No design changes are required.|
|**Solution description**|1.Changed the col width in the introduction.md file|
|**Output screenshots**||
|**Areas affected and ensured**|<ul><li>Changes in the introduction.md file. Previous code didn't affected and ensured in end.</li></ul>|
|**Test cases**|Check the site locally.|
|**Testbed sample location**|-|
|**Additional CheckList**|<ul><li>Did you run the automation against your fix? No</li><li>Is there any API name change?No</li><li>Is there any existing behavior change of other features due to this code change? No.</li><li>Does your new …

174643-Tabletextalignmentissue-dev

---

ej2-javascript/js/introduction.md
ej2-javascript/ts/introduction.md

| Title | Description |
| -------- | -------- |
|**Task Link**|https://dev.azure.com/Syncfusion-Infrastructure/Install/_workitems/edit/175165|
|**Analysis and design**|1. Analyzed the details in the task.<br/>2. No design changes are required.|
|**Solution description**|1.Changed the col width in the introduction.md file|
|**Output screenshots**|-|
|**Areas affected and ensured**|<ul><li>Changes in the introduction.md file. Previous code didn't affected and ensured in end.</li></ul>|
|**Test cases**|Check the site locally.|
|**Testbed sample location**|-|
|**Additional CheckList**|<ul><li>Did you run the automation against your fix? No</li><li>Is there any API name change?No</li><li>Is there any existing behavior change of other features due to this code change? No.</li><li>Does your new …

175165-Changecolumnwidth-hotfix

---

ej2-javascript/ej2-javascript-common-toc.html
ej2-javascript/ej2-typescript-common-toc.html

Removed Release Notes from toc

documentation(843780): Removed Release Notes from toc

---

ej2-javascript/code-snippet/common/change-theme-cs1/systemjs.config.js
ej2-javascript/code-snippet/common/function-template-cs1/systemjs.config.js
ej2-javascript/code-snippet/common/function-template-cs2/systemjs.config.js
ej2-javascript/code-snippet/common/getting-started-cs1/systemjs.config.js
ej2-javascript/code-snippet/common/locale-cs1/systemjs.config.js
ej2-javascript/code-snippet/common/material3-cs1/systemjs.config.js
ej2-javascript/code-snippet/common/script-template-cs1/systemjs.config.js
ej2-javascript/code-snippet/common/state-persistence-template-cs1/systemjs.config.js
ej2-javascript/code-snippet/common/string-template-cs1/systemjs.config.js

Included notification package reference in systemjs.config.js for Javascript framework

documentation(849289): Add the package to the systemjs.config.js

---

ej2-javascript/ej2-typescript-common-toc.html
ej2-javascript/ts/security-advisory.md

Added the security advisory in JS2 controls.

documentation(EJ2-851267): Added the security advisory in JS2 controls.

---

ej2-javascript/common/accessibility.md

Need to update accessibility document.
We have not updated accessibility document with reviewed content.
Updated the document with WCAG, Section 508 and ADA content.
No area is affected due to this changes.

feature(850964): Need to updated accessibility document

---

ej2-javascript/js/licensing/license-key-registration.md
ej2-javascript/ts/licensing/license-key-registration.md

I have modified the license registration content for better understanding.

Feature(379033): I have modified the license registration content

---

ej2-javascript/appearance/icons.md

###Description
Added width for icon panel since it was hard to scroll
- Did you run the automation against your fix? NA
- Is there any API name change? No
- Is there any existing behavior change of other features due to this code change? No
- Does your new code introduce new warnings or binding errors? No
- Does your code pass all FxCop and StyleCop rules? NA
- Did you record this case in the unit test or UI test? No

534670 : Added Width setting for icons panel

---

ej2-javascript/common/accessibility.md

WCAG version is missing in the accessibility document and some component link are missed.
WE have not verified the accessibility document are having proper WCAG version.
Added WCAG version in the accessibility document and added component link.
Tag label `update-guideline-coreteam` or `update-guideline-productteam`. 
Provide details about the areas or combinations that have been tested against this code changes.
If yes, provide the breaking commit details / MR here. 
Check and update the link of the component and version of WCAG for every release.
Feature matrix document updated
Automation details - Mark `Is Automated` field as (Yes, Manual, Not Applicable) in corresponding JIRA task once the bug is automated. 
If the same issue is reproduced in ej2, what will you do?
Is this common issue …

864782: Need to modify accessibility document

---

ej2-javascript/js/licensing/license-key-registration.md
ej2-javascript/ts/licensing/license-key-registration.md

I have edited the register license method information for better understanding. 

Feature(864274):Modified the license content

---

ej2-javascript/ts/licensing/license-key-registration.md
ej2-javascript/ts/licensing/licensing-troubleshoot.md

I have edited the register license method information for better understanding in npx and added content in license troubleshooting page. 

Feature(865439): Added info about NPX

---

ej2-javascript/common/accessibility.md

Need to update common accessibility document with component's accessibility document
[868718](https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/868718)
NA
NA
Feature matrix document updated against this feature and committed in this [common location] (https://syncfusion.sharepoint.com/sites/EJ2ProductOwners/Shared%20Documents/Forms/AllItems.aspx?viewid=ae81c682%2D3d0f%2D462a%2Db8ec%2D7358748d489d&id=%2Fsites%2FEJ2ProductOwners%2FShared%20Documents%2FGeneral%2FFeature%20Matrix%20%2D%20Documents) . 
Provide the details about the areas or combinations which have been tested against this code changes.
Draft the test cases in excel and attach it in the MR itself. The automation must be covered based on this positive and worst-case test-cases.   
Mark 'Is Automated' field as (Yes, …

868718: Need to update common accessibility document with component's accessibility document

---

ej2-javascript/common/security-considerations.md

867190: Changed the samples folder name

867190: Changed the samples folder name

---

ej2-javascript/common/security.md
ej2-javascript/ej2-javascript-common-toc.html
ej2-javascript/ej2-typescript-common-toc.html

867190: Changes are added in security considerations documentation

867190: Changes are added in security considerations documentation

---

ej2-javascript/common/security.md

875285: Changed the code snippet

875285: Changed the code snippet

---

ej2-javascript/ts/introduction.md

Need to add the div tag for components in Typescript documentation.
Added the div tag for components in Typescript documentation.
NA
* Adding this file support will not affect any other existing feature. 
This may vary for different teams or products. Check with your scrum masters.
•	Did you run the automation against your fix? - yes
•	Is there any API name change? - No
•	Is there any existing behavior change of other features due to this code change? - No
•	Does your new code introduce new warnings or binding errors? - No
•	Does your code pass all FxCop and StyleCop rules? - yes
•	Did you record this case in the unit test or UI test? – NA

868120: Add new components in Js and Ts documentation.
